### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [cagelight/jedi-academy-blender-suite#4]
_

**Comment by cagelight** [comment]
Could you check to make sure you don't have multiple installations of the plugin? or perhaps an older installation that's conflicting with a newer one?

**Comment by briancullinan** [comment]
@cagelight Interesting, I closed blender and opened it again and it enabled OK. I have this exact same problem with Jupyter and most languages, can't redefine classes. Thank you. And thanks for the hard work on this!
