### ISSUE TITLE
Vertices triple on an object

### ISSUE THREAD

**Issue by TheHusseler** [cagelight/jedi-academy-blender-suite#7]
Found an issue when using a functioning .glm model, that other people using blender 2.7 have been able to import/export with no problems. If I import it, make no edits, and export it again, then one of the objects triples in vertices count and is no longer usable in modview or jka. Again, the same setup is usable with 2.7 and the associated jka blender suite. This makes it functionally impossible to edit said model, even reducing the number of vertices on the object by a large amount produced no usable results

**Comment by cagelight** [comment]
Provide the model, please.

**Comment by TheHusseler** [comment]
https://www.mediafire.com/file/m7oddqn28zoeog8/NewGuard.zip/file
Here's a zip of the .glm, .skin and some textures.
